# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.check_int64 <- function(is_signed, integer64) {
    .Call(`_RcppSimdJson_check_int64`, is_signed, integer64)
}

.validateJSON <- function(filename) {
    .Call(`_RcppSimdJson_validateJSON`, filename)
}

parseExample <- function() {
    invisible(.Call(`_RcppSimdJson_parseExample`))
}

.cppVersion <- function() {
    .Call(`_RcppSimdJson_cppVersion`)
}

.unsupportedArchitecture <- function() {
    .Call(`_RcppSimdJson_unsupportedArchitecture`)
}

