# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Deserialize JSON into R Objects
#'
#' @param json \code{character(1L)}
#'
#' @param json_pointer \code{character(1L)}, default: \code{""}
#'
#' @param empty_array default: \code{NULL}. Any R object to return for empty JSON arrays.
#'
#' @param empty_object default: \code{NULL}. Any R object to return for empty JSON objects.
#'
#' @param simplify_to default: \code{0}. Maximum simplification level.
#'   0=dataframe, 1=matrix, 2=vector, 3=list
#'
#' @param type_policy default: \code{0}. Level of type strictness.
#'   0=anything goes, 1=merge integers/doubles, 2=strict
#'
#' @param int64_r_type default: \code{0} How to return big integers to R.
#'   0=double, 1=string, 2=bit64::integer64
#'
#' @keywords internal
#'
.deserialize_json <- function(json, json_pointer = "", empty_array = NULL, empty_object = NULL, simplify_to = 0L, type_policy = 0L, int64_r_type = 0L) {
    .Call(`_RcppSimdJson_deserialize_json`, json, json_pointer, empty_array, empty_object, simplify_to, type_policy, int64_r_type)
}

.exceptions_enabled <- function() {
    .Call(`_RcppSimdJson_exceptions_enabled`)
}

.check_int64 <- function() {
    .Call(`_RcppSimdJson_check_int64`)
}

.validateJSON <- function(filename) {
    .Call(`_RcppSimdJson_validateJSON`, filename)
}

#' Simple JSON Parsing Example
#'
#' This example is adapted from a blogpost announcing an earlier \sQuote{simdjson}
#' release. It is of interest mostly for the elegance and conciseness of its C++
#' code rather than for any functionality exported to R.
#'
#' The function takes no argument and returns nothing.
#'
#' @examples
#' parseExample()
parseExample <- function() {
    invisible(.Call(`_RcppSimdJson_parseExample`))
}

.cppVersion <- function() {
    .Call(`_RcppSimdJson_cppVersion`)
}

.unsupportedArchitecture <- function() {
    .Call(`_RcppSimdJson_unsupportedArchitecture`)
}

