# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.deserialize_json <- function(json, json_pointer = "", empty_array = NULL, empty_object = NULL, single_null = NULL, error_ok = FALSE, on_error = NULL, simplify_to = 0L, type_policy = 0L, int64_r_type = 0L) {
    .Call(`_RcppSimdJson_deserialize_json`, json, json_pointer, empty_array, empty_object, single_null, error_ok, on_error, simplify_to, type_policy, int64_r_type)
}

.load_json <- function(file_path, json_pointer = "", empty_array = NULL, empty_object = NULL, single_null = NULL, error_ok = FALSE, on_error = NULL, simplify_to = 0L, type_policy = 0L, int64_r_type = 0L) {
    .Call(`_RcppSimdJson_load_json`, file_path, json_pointer, empty_array, empty_object, single_null, error_ok, on_error, simplify_to, type_policy, int64_r_type)
}

.exceptions_enabled <- function() {
    .Call(`_RcppSimdJson_exceptions_enabled`)
}

.check_int64 <- function() {
    .Call(`_RcppSimdJson_check_int64`)
}

.validateJSON <- function(filename) {
    .Call(`_RcppSimdJson_validateJSON`, filename)
}

#' Simple JSON Parsing Example
#'
#' This example is adapted from a blogpost announcing an earlier \sQuote{simdjson}
#' release. It is of interest mostly for the elegance and conciseness of its C++
#' code rather than for any functionality exported to R.
#'
#' The function takes no argument and returns nothing.
#'
#' @examples
#' parseExample()
parseExample <- function() {
    invisible(.Call(`_RcppSimdJson_parseExample`))
}

.cppVersion <- function() {
    .Call(`_RcppSimdJson_cppVersion`)
}

.unsupportedArchitecture <- function() {
    .Call(`_RcppSimdJson_unsupportedArchitecture`)
}

